### ISSUE TITLE
High Bandwidth Usage

### ISSUE THREAD

**Issue by carydias** [MathiasSvendsen/Himawari#2]
Thanks for the code!

However using this on a 1440p resolution phone and the app has used ~500mb in only an hour and a half:
http://i.imgur.com/V78xiY3.png

If it's not too much hassle can an option be added to force the zoom level in the url?  I'm running it at ~0.8 as it is currently, so an 1100px image (z2) would probably suit and 1/4 the data usage.

**Comment by MathiasStokholm** [comment]
Hi,

Thanks for commenting. The forced zoom level should be pretty straightforward to implement. I'll see if I have some spare time this weekend.
